### ISSUE TITLE
Can't select newly created video

### ISSUE THREAD

**Issue by frankiechz** [uzysjung/UzysAssetsPickerController#17]
When creating a new video, the video appears in the collection view grid but the new video is not selectable. 

Notes:
1. New created photos do work.
2. This is only when maximumNumberOfSelectionMedia is set.
3. collectionView:didSelectItemAtIndexPath is not being called in this circumstance.
4. This is with the latest commit: 90d9df133e.
5. This happens on both iOS 8.0.2 and 7.1.2. (Tested on devices.)

Has anyone seen this or can lead me in the right direction to getting it fixed?

Thanks,
Frankie

**Comment by mdaymond** [comment]
This seems to happen again on iOS 8.3
