### ISSUE TITLE
Error when using in Swift with CocoaPods V 0.36 Beta2

### ISSUE THREAD

**Issue by evermeer** [uzysjung/UzysAssetsPickerController#30]
When using CocoaPods with Swift libraries you have to use V 0.36 (beta)
This will make a dynamic framework from all the pods.
If you Add UzysAssetsPickerController then there is a problem when using it.
After adding the following line to the ..Bridgin-Header.h
   #import <UzysAssetsPickerController/UzysAssetsPickerController.h>
Then if you add the UzysAssetsPickerControllerDelegate to a class and implement the ditFinisPickerAssets then it will give the error:  Use of undeclared type 'UzysAssetsPickerController'
The strange thing is that if you only create a value of type UzysAssetsPickerController without adding the delegate you won't get that error.

**Comment by uzysjung** [comment]
please check merge request #28 It will be updated sooner or later

**Comment by evermeer** [comment]
Great! Can't wait for that :+1:

**Comment by uzysjung** [comment]
Thanks for the reporting. :+1:

**Comment by evermeer** [comment]
I can confirm that it does work (sort of). I did that by specifying that I wanted the head by putting this in my pod file:
pod 'UzysAssetsPickerController', :head
But then you do have to manually include the UzysAssetsPickerController.xib into your project. I think there is an issue when using resources and dynamic frameworks.

**Comment by evermeer** [comment]
I just added UzysAssetsPickerController as a component for the demo for https://github.com/evermeer/EVCloudKitDao

**Comment by uzysjung** [comment]
Thank you for using UzysAssetsPickerController. 
I think cocoapods has also some issue missing resources with Xcode6 and Objective C.
If I have updated , I will let you know. :+1:
