### ISSUE TITLE
IOS 7.1 iPhone 4S setupCollectionView crash!

### ISSUE THREAD

**Issue by scaupdc** [uzysjung/UzysAssetsPickerController#33]
But it works fine before this version......

**Comment by uzysjung** [comment]
There's some mistake. I will add new version 0.9.7 ASAP

**Comment by scaupdc** [comment]
Thanks.Waiting for the new version.

**Comment by scaupdc** [comment]
Would you say something about this mistake?

**Comment by uzysjung** [comment]
I called [[UIScreen mainScreen] nativeScale] in IOS7
#define IS_IPHONE_6P_IOS8 (IS_IPHONE && IS_IOS8 &&([[UIScreen mainScreen] nativeBounds].size.height/[[UIScreen mainScreen] nativeScale]) == 736.0f)
