### ISSUE TITLE
Warning Method 'uzysAssetsPickerController:didFinishPickingAssets:' in protocol 'UzysAssetsPickerControllerDelegate' not implemented

### ISSUE THREAD

**Issue by DimonDeveloper** [uzysjung/UzysAssetsPickerController#37]
Why i have warning? 

Method 'uzysAssetsPickerController:didFinishPickingAssets:' in protocol 'UzysAssetsPickerControllerDelegate' not implemented 

And - (void)UzysAssetsPickerController:(UzysAssetsPickerController *)picker didFinishPickingAssets:(NSArray *)assets not working.

**Comment by uzysjung** [comment]
please check 
V0.9.6 - changing Delegate Method name because of supporting Swift. #28
