### ISSUE TITLE
Change xib color 

### ISSUE THREAD

**Issue by boboRAY** [uzysjung/UzysAssetsPickerController#40]
Hi:
I found out this perfect lib for me. I'm using Cocoapods so i can't adjust .xib to customize the view. Can u move those `IBOutlet` property in `UzysAssetsPickerController.m` to `UzysAssetsPickerController.h` to make them public?
Thanks a lot!

**Comment by uzysjung** [comment]
you can customize xib in cocoapod project. it will work :) but you should fix the version in podfile

**Comment by boboRAY** [comment]
Hi
But I'm using this pods in  team developing. If i customize xib in pods file, my partner won't get the same customize ( since pod install from github immediately, not my version )

**Comment by uzysjung** [comment]
Hi , in this case. add UzysAssetsPickerController Library directory to your project. and customize xib.
you do not use cocoapod.
