### ISSUE TITLE
Can't select newly created video or photo

### ISSUE THREAD

**Issue by mdaymond** [uzysjung/UzysAssetsPickerController#42]
When creating a new video or photo, the media appears in the collection view grid but the new media is not selectable.

Notes:
1. This is using the demo code
2. collectionView:didSelectItemAtIndexPath is not being called in this circumstance.
3. I can confirm this on iOS 8.3 for sure.

Has anyone seen this or can lead me in the right direction to getting it fixed?

**Comment by uzysjung** [comment]
today I checked Latest version 0.9.7.
it works well. could you explain more ?

**Comment by mdaymond** [comment]
I will check again.  My config is the latest Xcode and swift 1.2

**Comment by uzysjung** [comment]
Please check the delegate name. Didfinish...

**Comment by uzysjung** [comment]
thanks for the reporting . bug fixed.
