### ISSUE TITLE
Can't done newly created video or photo

### ISSUE THREAD

**Issue by zeew** [uzysjung/UzysAssetsPickerController#43]
The newly created video or photo is display selected,but can not save it.(it should be choose again)

**Comment by uzysjung** [comment]
I checked Latest version 0.9.7 on iPhone6 (iOS8.3).
it works well. could you explain more ?

please check your UzysAssetsPickerController Version.

**Comment by zeew** [comment]
I checked Latest version 0.9.7 on iPhone5s (iOS8.12)
-----
The detail problem is this：
when the newly created video or photo be use, the newly item is selected,
and bottom -right button number is 1,
but the button can not be tap.

**Comment by intmain** [comment]
제가 풀리퀘 드린 부분에서 버그가 있는것 같습니다. 죄송합니다. ㅠ

선택 순서대로 array에 저장하는 기능을 넣으면서, 카메라로 찍은 asset을 거기에 포함하지 않았습니다. 

얼른 다시 풀리퀘 드리겠습니다.

**Comment by uzysjung** [comment]
Thanks for the bug reporting. I fixed bug. that caused by new feature (select order).
I would recommend you to use taged version not latest commit.
