### ISSUE TITLE
picked pictures get rotated

### ISSUE THREAD

**Issue by mdaymond** [uzysjung/UzysAssetsPickerController#45]
From what I can see this problem appears to be from any picture picked through this control.   Images appear to be rotated by either 90 or 180 degrees.   this is on iOS 8.3 and swift 1.2

**Comment by uzysjung** [comment]
I tested recent version. It works. 
and this lib is AssetPicker.
So it did not manipulate image.

**Comment by chlebta** [comment]
I get same issue when I use Camera to to take photo , this photo is rotated -90degree but when I select photo from gallery it work's fine
