### ISSUE TITLE
Delete photo from asset

### ISSUE THREAD

**Issue by chlebta** [uzysjung/UzysAssetsPickerController#47]
Hello, how to delete photo from the assets programmatically ? I've tried this but didn't worked  
```
[_picker delete:[_photoArray objectAtIndex:indexPath.row]]
```

**Comment by uzysjung** [comment]
iOS doesn't provide delete item in photo library

**Comment by chlebta** [comment]
Not from photo library but from selected photo in picker ( deselect an item programmatically )
