### ISSUE TITLE
Thumbnail scaling in popover

### ISSUE THREAD

**Issue by tylerjames** [uzysjung/UzysAssetsPickerController#49]
On iPad pickers should generally be shown in a popover. However with this lib the thumbnail size does not scale when shown in a popover. Consequently I can only see 1 1/2 pictures per row.

I should have some kind of setting for number of thumbnails per row and then they should scale appropriately to accommodate that number.

**Comment by uzysjung** [comment]
check pullrequest #48

you can find feature on master branch
