### ISSUE TITLE
README.md file function usage error spell

### ISSUE THREAD

**Issue by MrVokie** [uzysjung/UzysAssetsPickerController#51]
in your README.md file.
the function usage like this:
- (void)UzysAssetsPickerController:(UzysAssetsPickerController *)picker didFinishPickingAssets:(NSArray *)assets
{ ... }

but actually it should Use lower case first character( ) like this：
- (void)uzysAssetsPickerController:(UzysAssetsPickerController *)picker didFinishPickingAssets:(NSArray *)assets
{ ... }

**Comment by uzysjung** [comment]
Thanks
