### ISSUE TITLE
A Crash while  initWithNibName: bundle:

### ISSUE THREAD

**Issue by kos9kus** [uzysjung/UzysAssetsPickerController#53]
Arise a crash:
 Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/kos/Library/Developer/CoreSimulator/Devices/2C0792BB-88DE-40B3-B121-1DBA6466B45C/data/Containers/Bundle/Application/D7605932-AE36-439F-A727-F1C04DBC1CB6/adding_TI_item.app> (loaded)' with name 'UzysAssetsPickerController''

i installed a pod through CocaoPods and imported lib, compiling is fine but while initialisation there is crash. Maybe I should something include a reference  to my navigate panel of main project directly ?
Any ideas ?
Thanks in advance

**Comment by uzysjung** [comment]
Hi, I thinks it's not related problem with UzysAssetsPickerController.

In general, NSInternalInconsistencyException realted to storyboard and xib

you must not  insert UzysAssetPickerController lib's xib to your story board.

please read how to use UzysAssetPickerController 

if you composed nib using storyboard , you must call  xib like '[storyboard instantiateViewControllerWithIdenfier:@"name"]

**Comment by kos9kus** [comment]
I did it like:
UzysPicker = UzysAssetsPickerController()
self.presentViewController(UzysPicker!, animated: true) { () -> Void in
        }
it can be reason that the resource bundle of UzysAssetsPickerController  is located into Pods project ?

**Comment by uzysjung** [comment]
Did you use cocoapod? I tested 0.9.7 it works fine

**Comment by uzysjung** [comment]
check http://blog.cocoapods.org/CocoaPods-0.36/

iOS 8 introduced dynamic frameworks, and these allow code, images and other assets to be bundled together. Prior to iOS 8, CocoaPods were created as static libraries, which are just “fat” binaries. This means they contain several code instruction sets (e.g. i386 for the simulator, armv7 for devices, etc.), but they aren’t allowed to contain any resources such as images or assets.

**Comment by kos9kus** [comment]
I use cocoapod 0.37.1 version
and the running is on the ios 8.4

**Comment by uzysjung** [comment]
cocoapods doesn't fully support Swift.

but theres one solution

create your pod file like below
=======
platform :ios, '8.0'
use_frameworks!
pod 'UzysAssetsPickerController', '~> 0.9.7'
=======

and change code of UzysAssetsPickerController.m Line:64

    self = [super initWithNibName:@"UzysAssetsPickerController" bundle:[NSBundle bundleForClass:[UzysAssetsPickerController class]]];

It works. :)

**Comment by uzysjung** [comment]
or check v0.9.8

**Comment by kos9kus** [comment]
Thanks for reply
I did it you recommended, the nib loads well but the several assets of image don't display.
It's really weird, why some images are displayed , whereas some images aren't displayed...

**Comment by uzysjung** [comment]
That is the reason that you turn on icloud photo backup and you also turn on optimize storage

**Comment by kos9kus** [comment]
I don't mean my personal photos, I'm talking about your image assets,
Look at a screenshot:
![screen shot 2015-07-21 at 12 44 49](https://cloud.githubusercontent.com/assets/7373566/8797788/72a6f084-2fa6-11e5-99d7-1c08fd803b64.png)

The some of them are not display on the view when it's loaded, they are not loaded (like nil)
Thanks
