### ISSUE TITLE
The titleLabel on the bottom can not show complete

### ISSUE THREAD

**Issue by chelongfei** [uzysjung/UzysAssetsPickerController#55]
when you set the maximumNumberOfSelectionMedia=1,then the title on the bottom can not show complete,just like this
![2015-07-22 5 21 15](https://cloud.githubusercontent.com/assets/12293157/8822165/15dc5ff6-3096-11e5-99aa-2d7011bf8451.png)
and I  suggest that you can give a method to set the title on the bottom,such as "pick a photo",thank you for give us  such a good thing to pick a photo!

**Comment by uzysjung** [comment]
thanks for the reporting.
I fixed it. 

and if you want to change string in Xib, you can use localized stringfile.

I implemented like below,
 self.labelSelectedMedia.text = NSLocalizedStringFromTable(@"Choose videos", @"UzysAssetsPickerController", nil);
