### ISSUE TITLE
Picture select in second time.

### ISSUE THREAD

**Issue by MrVokie** [uzysjung/UzysAssetsPickerController#56]
Here is a question:
I selected two pictures at first time.
is that possible to make the two pictures are selected when I enter the picture select view controller again?

**Comment by uzysjung** [comment]
Yes, it possible if you save selected pictures asset url and need to customize

**Comment by MrVokie** [comment]
I don't have found the sample code In your project.
how to save asset url?
how to customize?

**Comment by uzysjung** [comment]
there's no example. 
if you refer to codes that select photo after taking photo, you can make it.

**Comment by MrVokie** [comment]
thanks a lot. I am reading your source code for more help.

**Comment by uzysjung** [comment]
it will help you. check this out. 
(void)saveAssetsAction:(NSURL *)assetURL error:(NSError *)error isPhoto:(BOOL)isPhoto
