### ISSUE TITLE
Analyzer warnings - CRColorSpaceRef and CGGradientRef not released

### ISSUE THREAD

**Issue by CraZyMuffinIPC** [uzysjung/UzysAssetsPickerController#61]
UzysAssetsViewCell.m line 117 and 118 both should be released after they are used with CGColorSpaceRelease(baseSpace) and CGGradientRelease(gradient) respectively.

**Comment by uzysjung** [comment]
Thank you for your interest . You are right.
Sooner or later I have a plan to make new version of AssetsPicker.
